### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by haircommander**
as title says

### CODE REVIEW

**Comment by vrothberg** [comment]
@haircommander, can you add a changelog to the 1.0.0 commit?
I use the following git alias for such purposes:
```
alias changelog='git log --no-merges --format="  * %s"'
```

**Comment by vrothberg** [comment]
I mean *bash* alias for sure :)

**Comment by haircommander** [comment]
@vrothberg I added as a separate commit because I would have been remiss if only 1.0.0 had a changelog :)

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests

**Pull request merged**
