### PR TITLE
cgroup: do not write twice the oom file

### PR DESCRIPTION
**Pull request by giuseppe**
if a persist_path was provided, then use only that to write the oom file instead of creating it also in the current working directory.

Closes: https://github.com/containers/conmon/issues/504

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Thanks, LGTM

I find it weird that the function is named write and that the error says write too but it really just creates an empty file, but this is pre-existing so I don't mind.

**Comment by giuseppe** [comment]
> I find it weird that the function is named write and that the error says write too but it really just creates an empty file, but this is pre-existing so I don't mind.

good idea, I've renamed it to `create_oom_file`

**Comment by giuseppe** [comment]
@haircommander PTAL

**Comment by giuseppe** [comment]
maybe we can fix it in Podman, and run the conmon process from the bundle path itself, or the persistent dir

**Comment by giuseppe** [comment]
alternative fix for Podman: https://github.com/containers/podman/pull/23243

**Pull request closed without merging**
