### PR TITLE
Add CRI-O integration test GitHub action

### PR DESCRIPTION
**Pull request by saschagrunert**
This adds a GitHub action for integration testing the latest CRI-O
master against the conmon change to verify its impact.

### CODE REVIEW

**Comment by saschagrunert** [comment]
A first run can be found within my fork: https://github.com/saschagrunert/conmon/runs/2057914238?check_suite_focus=true

**Comment by saschagrunert** [comment]
Encountered a first issue:
```
Response error: command error: EOF, stdout: , stderr: , exit code -1
```

**Comment by saschagrunert** [comment]
Exec is still broken on the master as it seems.

**Comment by saschagrunert** [comment]
The tests works when moving back to the latest conmon release.

**Comment by haircommander** [comment]
LGTM

**Pull request merged**
