### PR TITLE
Remove go.sum file and add go.mod

### PR DESCRIPTION
**Pull request by saschagrunert**
We excluded the go.mod via the .gitignore file, which should not be
correct. Beside that, we do not need a go.sum file because we do not
have external dependencies yet.

### CODE REVIEW

**Comment by haircommander** [comment]
ah that makes sense I didn't notice go.mod wasn't included
while we're at it, can you remove the
```
# the || true is to make this call idempotent, in case we already have initialized the module
go mod init || true
```
from contrib/cirrus/integration_test.sh ? that should fix the config task

**Comment by saschagrunert** [comment]
> ah that makes sense I didn't notice go.mod wasn't included
> while we're at it, can you remove the
> 
> ```
> # the || true is to make this call idempotent, in case we already have initialized the module
> go mod init || true
> ```
> 
> from contrib/cirrus/integration_test.sh ? that should fix the config task

Hah, yeah sure that makes sense. Fixed that, too. :+1:

**Comment by haircommander** [comment]
oop, sorry, there's also an instance in .cirrus.yml

**Comment by saschagrunert** [comment]
> oop, sorry, there's also an instance in .cirrus.yml

No worries, fixed that too :+1:

**Comment by rhatdan** [comment]
Any idea why the static builds are failing?

**Comment by saschagrunert** [comment]
> Any idea why the static builds are failing?

The master rebase should fit the issue.

**Comment by haircommander** [comment]
LGTM

**Pull request merged**
