### PR TITLE
Add Kubernetes e2e tests as GitHub action

### PR DESCRIPTION
**Pull request by saschagrunert**
This adds a GitHub actions test suite to run a subset of the node e2e
tests with the locally built version of conmon.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by haircommander** [comment]
LGTM, but we've got a merge conflict :)

**Comment by saschagrunert** [comment]
Resolved the conflict.

**Comment by haircommander** [comment]
LGTM

**Pull request merged**
