### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by bschacht**
recieved -> received

### CODE REVIEW

**Comment by vrothberg** [comment]
Thanks for the contribution, @bschacht! Could you sign your commit (e.g., `$ git commit -s --amend`) and repush? Besides that, LGTM.

**Comment by bschacht** [comment]
> Thanks for the contribution, @bschacht! Could you sign your commit (e.g., `$ git commit -s --amend`) and repush? Besides that, LGTM.

done!

**Comment by vrothberg** [comment]
Thanks! @haircommander @giuseppe PTAL

**Comment by vrothberg** [comment]
@bschacht https://github.com/containers/conmon/pull/31/commits/34f25ade060d5e829448823b235db3f945a0eecd is still not signed. Did you push the right commit?

**Comment by giuseppe** [comment]
change LGTM, but it still missing the Signed-off-by

**Comment by bschacht** [comment]
> @bschacht [34f25ad](https://github.com/containers/conmon/commit/34f25ade060d5e829448823b235db3f945a0eecd) is still not signed. Did you push the right commit?

sorry, I though you meant cryptographically signing. Its now signed and signed off ;)

**Comment by giuseppe** [comment]
LGTM

**Comment by haircommander** [comment]
LGTM thanks for the patch!

**Pull request merged**
