### PR TITLE
Initialize the endpoint for attach before calling fork.

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
This way, when an error occurs in the attach endpoint logic, conmon can exit immediately without having to clean up the child process. Because the exit happens before forking, the child process doesn't have to be cleaned up at all.

This doesn't solve the core problem that no cleanup is being done on exit but after looking into the code making sure everything is cleanup up correctly is a bit out of my league and is better done by someone more familiar with the code. 

As an aside (and this is absolutely not meant in a bad way), I found the code rather hard to understand with the massive single conmon.c file with very a large main function, lots of globals/callbacks and no clearly defined point of cleanup. I was also expecting a lot more inline documentation on what conmon does and how its implementation works. I find it hard to make any kind of substantial changes to a project without this information at hand.

I didn't test the change yet locally, I'm assuming CI will kick off once I make the PR to verify if this breaks anything.

### CODE REVIEW

**Comment by haircommander** [comment]
Thanks for the PR @DaanDeMeyer 
> As an aside (and this is absolutely not meant in a bad way), I found the code rather hard to understand with the massive single conmon.c file with very a large main function, lots of globals/callbacks and no clearly defined point of cleanup. I was also expecting a lot more inline documentation on what conmon does and how its implementation works. I find it hard to make any kind of substantial changes to a project without this information at hand.

I (one of the conmon maintainers) absolutely agree. It's high on my list of wants to refactor conmon to be more readable. I appreciate you digging through the code

Change LGTM at a glance

**Comment by giuseppe** [comment]
LGTM

I've restarted the failing tests

**Comment by rhatdan** [comment]
Thanks @DaanDeMeyer 
Any one wanting to rewrite/refactor conmon would be appreciated.

**Comment by saschagrunert** [comment]
> Thanks @DaanDeMeyer
> Any one wanting to rewrite/refactor conmon would be appreciated.

Sounds like another great opportunity to rewrite conmon in Rust. :innocent:

**Pull request merged**
