### PR TITLE
include name and tag of a container into journald message for syslog [WIP]

### PR DESCRIPTION
**Pull request by tobwen**
# summary
When writing logs from _conmon_ into _journald_ and post-process the journal with _rsyslog_ or others, there's no way to filter logs from plain _syslog_ messages. This PR prefixes the container's name and its tags (if set) to each message. See: https://github.com/containers/conmon/issues/271

# syntax
`container-name[container-tag]`

# examples
## container-name has been set, container-tag has been set
`Jun  7 00:00:00 debian conmon[666]: podman-nginx[test-buid-20210706] message`

## only container-name has been set
`Jun  7 00:00:00 debian conmon[667]: podman-nginx It works.`

## only container-tag has been set
`Jun  7 00:00:00 debian conmon[668]: [test-buid-20210706] It works.`

## neither ... nor ... has been set
`Jun  7 00:00:00 debian conmon[669]: It works.`

### CODE REVIEW

**Comment by haircommander** [comment]
thanks for the PR @tobwen LGTM

**Comment by haircommander** [comment]
one thing of note: I wonder if this break compatibilty with the docker journald log driver (on which this behavior was based)

**Comment by tobwen** [comment]
> one thing of note: I wonder if this break compatibilty with the docker journald log driver (on which this behavior was based)

True. I can try to add a switch. But I'd also need to make changes to _podman_ then (`--log-opt`).

**Comment by haircommander** [comment]
> > one thing of note: I wonder if this break compatibilty with the docker journald log driver (on which this behavior was based)
> 
> True. I can try to add a switch. But I'd also need to make changes to _podman_ then (`--log-opt`).

yeah I think that'd be best

**Comment by tobwen** [comment]
Implementation is too complicated and the audience is too little. Closing.

**Pull request closed without merging**
