### PR TITLE
Packit: initial enablement

### PR DESCRIPTION
**Pull request by lsm5**
This commit will run Copr builds on every PR against all active
releases of Fedora, thus allowing buildability checks before the
PR merges.

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

EDIT: s/Koji scratch/Copr/

### CODE REVIEW

**Comment by lsm5** [comment]
@edsantiago packit is largely happy here. Couple of jobs are in progress but they should finish soon. Don't think you deal with conmon usually, but this should be another good data point.

@haircommander PTAL :)

**Comment by lsm5** [comment]
> Can't tell if i386/s390x are hung or just slow. Regardless, though, multiple test failures.

both jobs are successful, packit people said it's apparently some issue with the github API. Other test failures are likely something else. I'll rerun them.

**Comment by haircommander** [comment]
LGTM thanks!

**Comment by lsm5** [comment]
@haircommander do you know whatsup with the integration test failures? I'm surely not to blame this time :laughing:

**Comment by lsm5** [comment]
@haircommander thanks a lot!

**Comment by lsm5** [comment]
@haircommander btw, do let me know if this causes you any pain in other PRs, we're working on bringing in packit to our repos in stages. ATM, adding rpm build checks for fedora, maybe later even include gating tests and stuff, if things don't turn out to be a PITA.

**Pull request merged**
