### PR TITLE
ctrl: drop fifo perms to 0660

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
@giuseppe @mheon any podman situations you'd worry about this? AFAIU podman doesn't change the user of conmon so we shouldn't need the last 6

**Comment by mheon** [comment]
I don't think so? All the user-mapping shenanigans that could cause issues only happen once the OCI runtime execs.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
