### PR TITLE
[DO NOT MERGE] Packit test

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by lsm5** [comment]
@haircommander any reason cirrus tasks for fedora-33 and 34 have been kept on? :smile:

**Comment by lsm5** [comment]
> @haircommander any reason cirrus tasks for fedora-33 and 34 have been kept on? smile

ahh that's what https://github.com/containers/conmon/pull/368 addresses

**Comment by lsm5** [comment]
ugh, packit jobs have been stuck for a day now. Need some packit eyes.

**Comment by cevich** [comment]
Any news on this @lsm5 ?

**Comment by lsm5** [comment]
Nothing apart from the referenced packit issue. Try repushing.

**Comment by lsm5** [comment]
@cevich woah, packit's all good now. Might have been a temporary hiccup. Do let me know the next time you see this .

**Pull request closed without merging**
