### PR TITLE
Release v2.0.2

### PR DESCRIPTION
**Pull request by vrothberg**
See title.

PTAL @rhatdan @giuseppe 

Once that's merged, we can cut the release.

Fixes: https://github.com/containers/conmon/issues/72

### CODE REVIEW

**Comment by vrothberg** [comment]
My working day is about to end. Once it's merged, feel free to take over and finish the release.

**Comment by haircommander** [comment]
LGTM

**Comment by rhatdan** [comment]
I created a release for this, @lsm5 Does this automatically trigger new packages for Fedora?

**Comment by lsm5** [comment]
haven't added conmon to autobuild yet, but I'll do it over the weekend.

**Pull request merged**
