### PR TITLE
Bump to version 0.3.0-dev

### PR DESCRIPTION
**Pull request by haircommander**
Tag 0.2.0 and bump to 0.3.0-dev

### CODE REVIEW

**Comment by haircommander** [comment]
let's wait on #22 and #27 before we merge this

**Comment by saschagrunert** [comment]
Hey, I guess we now can tag 0.2.0 on 59952292a3b07ac125575024ae21956efe0ecdfb, right?

**Comment by haircommander** [comment]
@saschagrunert hm, I guess but because we chronologically had 59952292a3b07ac125575024ae21956efe0ecdfb before 481a878cda3656b7256ed56ffe9f896ae99397cc the latter won't make it into the release :\ Let me see if I can fix it

**Comment by haircommander** [comment]
nevermind, my understanding of git is not whole yet haha, we are good I'll tag the release :)

**Comment by saschagrunert** [comment]
Great, thanks again!

**Pull request merged**
