### PR TITLE
Update to cri-o

### PR DESCRIPTION
**Pull request by haircommander**
c/conmon has fallen quite behind upstream cri-o. Let's catch up :)

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@haircommander you've some test issues.

**Comment by haircommander** [comment]
@TomSweeneyRedHat ah yes here is the trouble with testing a tool with tools that depend on it that @cevich was talking about. I have a fix in mind for this, but in the meantime, where is the cri-o version used in cirrus defined?

**Comment by TomSweeneyRedHat** [comment]
@cevich, you're up to bat for @haircommander 's cri-o version in cirrus question.

**Comment by cevich** [comment]
For this, since RHEL is used for CI, and because of OpenShift / cri-o version locking, we [handle it at runtime according to what's installed.](https://github.com/containers/conmon/blob/master/contrib/cirrus/lib.sh#L266-L275)

I'm planning something similar for Fedora using modularity.  There's a little bit of [monkey-patching need also](https://github.com/containers/conmon/blob/master/contrib/cirrus/integration_test.sh#L17-L21) since that test is broken in this particular version.  Though not ideal (we REALLY need dedicated/specialized conmon-tests here), this is the only way I could find to get the cri-o integration tests to pass :confused: 

If you have a better idea, I'm open to suggestions.  Took weeks to get ^^^ working reliably :confounded:

**Comment by haircommander** [comment]
@cevich my plan is to tackle conmon unit tests next sprint actually. You'll be gone so that'll give me some time to get something vaguely comprehensive. Then when you get back I'll have a nice plate of tests you can hand out to our cirrus bots :)

**Comment by cevich** [comment]
Lol, here's a hair-brained thought...I bet the changes you've got here will make my #13 pass (while simultaneously breaking RHEL).  As a test, try this (awful, unholy) thing:

```diff
diff --git a/.cirrus.yml b/.cirrus.yml
index fc3f108..a39d0d1 100644
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -20,8 +20,8 @@ env:
     ####
     #### Cache-image names to test with
     ###
-    PRIOR_RHEL_CACHE_IMAGE_NAME: "rhel-7-conmon-34e54ce8"
-    FEDORA_CACHE_IMAGE_NAME: "fedora-29-conmon-34e54ce8"
+    PRIOR_RHEL_CACHE_IMAGE_NAME: 'fedora-29-conmon-75ea13be'
+    FEDORA_CACHE_IMAGE_NAME: 'fedora-29-conmon-75ea13be'
     #PRIOR_FEDORA_CACHE_IMAGE_NAME: "fedora-28-notready"
     #RHEL_CACHE_IMAGE_NAME: "rhel-8-notready"
     #CENTOS_CACHE_IMAGE_NAME: "centos-7-notready"
```

**Comment by haircommander** [comment]
like that?

**Comment by cevich** [comment]
Ya, no idea if it'll work :confused: 

I have half a mind to drop running RHEL here all together, but that could suck if we ever want to test a needed backport for cri-o.  Either way, being pinned to the Fedora version of cri-o is probably much better for upstream development (here) than using RHEL.

We'll figure something out in any case.  Though heads-up: I'm on PTO for the next two weeks.

**Comment by cevich** [comment]
Eek! gosh, okay, well that most certainly did not work.  If you can make heads/tails why, more power to you.  All I see is a wall of unintelligible gobbledygook :confounded: 

Instead of using RPMs, if we pin conmon to a hard-coded cri-o SHA, then the CI here must compile cri-o.  Based on my experience with libpod, using the RPMs is much better from a dependency-tracking and real-world compatibility standpoint.

Honestly I don't have any good solutions here I'm afraid.  Did I mention it would be nice to only rely on some specialized conmon-tests? :smile:

**Comment by haircommander** [comment]
I think conmon tests are the move

**Comment by cevich** [comment]
If you have a mind to, please.  I'm not beholden to the current conmon CI setup in any way/form.  In fact, running specialized CI [tests direct from a docker file would be a fine and very simple solution.](https://cirrus-ci.org/guide/docker-builder/#dockerfile-as-a-ci-environment).  We could get rid of all the VMs and image-building and related scripts.  Would be fast.  Easy to maintain.  And trivial to expand.

**Comment by haircommander** [comment]
I think I'll need podman to create the containers that will then have be run directly with conmon with both runc and crun. Basically: check if conmon is being a good translator for image->runtime. I'll try to get that going with a dockerfile

**Comment by haircommander** [comment]
For the time being, I fixed the backwards compatibility problem. tests should pass and I'd like if this merged. PTAL @rhatdan @giuseppe @mrunalp @mheon

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Well this looks good.
 find /sys/kernel/ | wc
find: '/sys/kernel/security': Permission denied
find: '/sys/kernel/debug': Permission denied
find: '/sys/kernel/config': Permission denied
   5615    5615  213373
So I think for rootless we can ignore the mounts.

**Comment by rhatdan** [comment]
Wrong PR

**Comment by rhatdan** [comment]
@giuseppe @mrunalp @mheon PTAL

**Comment by haircommander** [comment]
@rhatdan @mheon needs manual merge, no bot here :)

**Comment by haircommander** [comment]
(and I don't have write access)

**Comment by mheon** [comment]
Done

**Pull request merged**
