### PR TITLE
Add static binary build to Cirrus CI

### PR DESCRIPTION
**Pull request by saschagrunert**
This PR adds the static binary build to the CI to ensure that everything works as expected.

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert why is this a WIP?

**Comment by saschagrunert** [comment]
> @saschagrunert why is this a WIP?

It's still not working yet :) I think I have to bootstrap podman on the GCE worker node...

**Comment by saschagrunert** [comment]
Ready for review, we now have the binary as build artifact in cirrus as well. Since we build it on top of alpine, we have this kind of divergence:

```
> file conmon
conmon: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, stripped
> ldd conmon
        statically linked
```

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.  @cevich WDYT?

**Comment by haircommander** [comment]
LGTM

**Comment by cevich** [comment]
looking

**Comment by cevich** [comment]
yep LGTM too

**Pull request merged**
