### PR TITLE
Cirrus: Update VMs w/ F34

### PR DESCRIPTION
**Pull request by cevich**
Update to F34, and Ubuntu 2104. Also modernize scripts to use
shared automation library functions.  Lastly, update
`hack/get_ci_vm.sh` to match functionality of other
containers-org. repositories.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@cevich Needs a rebase.

**Comment by cevich** [comment]
@haircommander @rhatdan [what's this failure mean.](https://github.com/containers/conmon/pull/256/checks?check_run_id=2468279547#step:6:228)?

**Comment by haircommander** [comment]
> @haircommander @rhatdan [what's this failure mean.](https://github.com/containers/conmon/pull/256/checks?check_run_id=2468279547#step:6:228)?

my guess is a flake, this code is unrelated to that

**Comment by cevich** [comment]
> my guess is a flake, this code is unrelated to that

Thanks.  I just pressed the "re-run all jobs" button, hopefully it will pass.

**Comment by cevich** [comment]
(rebased / force-pushed)

**Comment by cevich** [comment]
@haircommander :disappointed: Know anyone knows how to debug that test?

**Comment by haircommander** [comment]
k8s tests passed, another one failed. doesn't matter though, that was mostly a smoke test.

**Comment by haircommander** [comment]
LGTM

**Comment by haircommander** [comment]
thanks @cevich

**Pull request merged**
