### PR TITLE
Update CI VM Images to F36/F37

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
Ummm....help @lsm5 you're my only hope!

**Comment by lsm5** [comment]
weird, let me try a test PR here.

**Comment by cevich** [comment]
@haircommander do we care about the GHA workflow failures here?  If not, can I disable them?

**Comment by haircommander** [comment]
I like leaving them so I know where they're at, though they can be ignored 

I'm fine also ignoring packit. This should not really affect it.

LGTM, if this is ready I will merge @cevich

**Comment by cevich** [comment]
Yep it's ready.  Thanks.

**Pull request merged**
