### PR TITLE
don't leak syslog_identifier

### PR DESCRIPTION
**Pull request by jnovy**

### CODE REVIEW

**Comment by haircommander** [comment]
odd I could have sworn I did this.. thanks @jnovy can you sign off your commit

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@jnovy Sign your commit and then we can merge.

**Comment by haircommander** [comment]
replaced by https://github.com/containers/conmon/pull/362

**Pull request closed without merging**
