### PR TITLE
bump to 2.1.10

### PR DESCRIPTION
**Pull request by haircommander**

### CODE REVIEW

**Comment by giuseppe** [comment]
@lsm5 could we get the latest version on Fedora?

**Comment by lsm5** [comment]
> @lsm5 could we get the latest version on Fedora?

@giuseppe happening now https://koji.fedoraproject.org/koji/taskinfo?taskID=112398206

@haircommander are we gonna see many more updates to conmon meriting packit for downstream builds?

**Comment by lsm5** [comment]
I see this was released over a month ago. If we expect more releases / bugfixes, packit might still be worth it here.

**Comment by lsm5** [comment]
https://github.com/containers/conmon/pull/488

**Pull request merged**
