### PR TITLE
add log-global-size-max option to limit the total output

### PR DESCRIPTION
**Pull request by haircommander**
related to https://github.com/cri-o/cri-o/pull/5933 and https://github.com/cri-o/cri-o/security/advisories/GHSA-fcm2-6c3h-pg6j

### CODE REVIEW

**Comment by haircommander** [comment]
@saschagrunert @mrunalp @rhatdan @giuseppe PTAL

**Comment by rhatdan** [comment]
Does global add any value to the option.  Would --logs-size-max work?

**Comment by haircommander** [comment]
> Does global add any value to the option. Would --logs-size-max work?

we already have a log-size-max for the log rotation fields. the global is to differentiate the two

**Comment by rhatdan** [comment]
--logs-size-max 
versus --log-size-max  The s to differentiate the difference.

**Comment by haircommander** [comment]
ahh good idea. Unfortunately we've already shipped cri-o with the flag (and patches to conmon in openshift :see_no_evil: ) so it would end up being tricky to change it now

**Comment by giuseppe** [comment]
@haircommander would it be a breaking change for CRI-O if we change the behavior of `--log-global-size-max` to delete the oldest log file instead of stopping writing so that we could reuse it for https://github.com/containers/podman/issues/23191?

**Comment by giuseppe** [comment]
probably it is still cleaner to add a new option to specify the maximum number of files to keep around

**Comment by haircommander** [comment]
I'm not actually sure. It's used to limit the amount of output on exec probe requests to mitigate a CVE, and we never really concretely promised any behavior on which output would be returned if the exec probe exceeded the max. This change would change the behavior so that we get the end of output instead of beginning. I think you could make an argument in either direction. ultimately, a user would hit this situation if their execs were using *way* too much output, so I am inclined to say not a breaking change? WDYT @saschagrunert @mrunalp @kwilczynski @sohankunkerkar

**Comment by giuseppe** [comment]
yeah I had a quick look at it and I think it will be confusing. It is better a different option to control logs rotation

**Pull request merged**
