### PR TITLE
conmon: close the sync pipe before exit command

### PR DESCRIPTION
**Pull request by giuseppe**
before calling the exit command be sure the sync pipe is closed so
that the waiting process can stop waiting.

It solves an issue with Podman where the cleanup process could hang
since the container is already locked by the podman process waiting
on the sync pipe.  The reproducer here:

podman --runtime /bin/false run --rm  alpine true

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@mheon it should solve the issue I've seen with Podman

**Comment by haircommander** [comment]
LGTM

**Comment by mheon** [comment]
LGTM!

**Comment by giuseppe** [comment]
LGTM comment addressed

**Pull request merged**
