### PR TITLE
set locale to inherit environment

### PR DESCRIPTION
**Pull request by haircommander**
should fix https://bugzilla.redhat.com/show_bug.cgi?id=1893567

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
some background: https://bugzilla.gnome.org/show_bug.cgi?id=737137

**Comment by rhatdan** [comment]
LGTM
@containers/podman-maintainers PTAL
@giuseppe @mheon PTAL

**Comment by haircommander** [comment]
hm this did not do what I wanted... hold on this

**Comment by rhatdan** [comment]
@haircommander Any movement on this?

**Comment by giuseppe** [comment]
the fix is correct but it is not enough, we also need: https://github.com/containers/podman/pull/8935

**Review by giuseppe — APPROVED** [review]
LGTM

@haircommander feel free to merge as soon as you are fine with it

**Pull request merged**
