### PR TITLE
Update license to have owners and date of copyright

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
Fixes #30 
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
We also need to remove the `APPENDIX` note above that line to avoid confusion. See https://github.com/moby/moby/blob/master/LICENSE as an example. Once that's done, we can close #30.

**Comment by haircommander** [comment]
fixed here https://github.com/containers/conmon/pull/44

**Pull request merged**
