### PR TITLE
logging: new mode -l passthrough

### PR DESCRIPTION
**Pull request by giuseppe**
when passthrough is specified, the std stream files are passed directly to the container without conmon intercepting them.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@haircommander PTAL

**Comment by rhatdan** [comment]
LGTM
 But it would be nice if more tests were passing.

**Comment by giuseppe** [comment]
I see the following error in the tests: `<string>: [conmon:e]: No such log driver passthrough`.

Are we using the correct binary for the CI? :-)

**Comment by giuseppe** [comment]
> I see the following error in the tests: `<string>: [conmon:e]: No such log driver passthrough`.
> 
> Are we using the correct binary for the CI? :-)

I'll take a look at what is going on

**Comment by giuseppe** [comment]
rebased.

@haircommander does it look good to you?

**Comment by haircommander** [comment]
LGTM, thanks!

**Pull request merged**
