### PR TITLE
Bump to v2.0.28

### PR DESCRIPTION
**Pull request by haircommander**
as title says

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hmmm :thinking: 
```
Error: Can not copy signatures to docker-archive:/tmp/ubi8-init.tar: Storing signatures for docker tar files is not supported
Failure [44.485 seconds]
[BeforeSuite] BeforeSuite 
/home/runner/work/conmon/conmon/podman/test/e2e/common_test.go:108

  Expected
      <int>: 125
  to equal
```

**Comment by TomSweeneyRedHat** [comment]
Ugh, it's always the easy ones that fail....  Sorry @haircommander  and thanks.

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
Guess we need to push a `v2.0.28` tag as well.

**Comment by haircommander** [comment]
done!

**Comment by TomSweeneyRedHat** [comment]
Thanks all for the quick turn around on this one.

**Pull request merged**
