### PR TITLE
attach: always chdir

### PR DESCRIPTION
**Pull request by haircommander**
the age of symlinking the attach socket to generate the sunpath must end.
The path is simply too long, and it is quite hacky anyway.

when setting up the attach socket, chdir to the directory before linking the sunpath.
That allows us to drop this age old hack, and future proof the code

fixes: https://github.com/containers/conmon/issues/213

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
wait to merge for https://github.com/cri-o/cri-o/pull/4303 to be happy

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by haircommander** [comment]
tests passed this is ready for review

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
