### PR TITLE
correct winsz registration

### PR DESCRIPTION
**Pull request by haircommander**
when a container is not terminal, the ctrl_winsz_cb was never correctly registered,
as there was an ordering problem with the registration function. Fix this

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by haircommander** [comment]
alternative to https://github.com/containers/conmon/pull/283

Though, it's not totally clear to me that we even need to register this. Will we have window resizing if we're not running with a terminal?

**Comment by rhatdan** [comment]
@giuseppe @saschagrunert PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
code LGTM although I don't think we need this code if it is not a terminal.  I'd rather go with #283

**Comment by saschagrunert** [comment]
> Will we have window resizing if we're not running with a terminal?

Logically not.

**Comment by haircommander** [comment]
yeah let's go for that

**Pull request closed without merging**
