### PR TITLE
Bump to v2.0.15

### PR DESCRIPTION
**Pull request by haircommander**
As well as drop --output-file, as it's an incomplete solution

### CODE REVIEW

**Comment by mrunalp** [comment]
LGTM

**Comment by saschagrunert** [comment]
Hm can we enable prow for this repo? 🙂

**Comment by rphillips** [comment]
nit: Should the title of this issue be titled bumping to 2.0.16?

**Comment by haircommander** [comment]
> nit: Should the title of this issue be titled bumping to 2.0.16?

it's 2.0.16-dev, as in, we're developing on 2.0.16 right now. an old convention that CRI-O used to use



> Hm can we enable prow for this repo? slightly_smiling_face

one day, maybe. Though I'm not sure the advantage considering the development speed of conmon, other than it would save @rhatdan from trying /lgtm to no avail too :smile:

**Pull request merged**
