### PR TITLE
Build s390x binaries using musl libc

### PR DESCRIPTION
**Pull request by saschagrunert**
Building using musl until NixOS/nixpkgs#306473 is resolved.

Refers to cri-o/cri-o#7911

### CODE REVIEW

**Comment by saschagrunert** [comment]
/hold

Build failures incoming.

**Comment by saschagrunert** [comment]
/unhold 

All static builds are green now.

**Comment by saschagrunert** [comment]
@rhatdan @haircommander PTAL

Can we cut a new conmon release after that? (I can do if we agree).

**Comment by haircommander** [comment]
yeah makes sense to me! thanks :)

**Pull request merged**
