### PR TITLE
ci: bump to go 1.17

### PR DESCRIPTION
**Pull request by haircommander**
Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
CI isn't happy, but the changes LGTM

**Comment by haircommander** [comment]
> CI isn't happy, but the changes LGTM

CI is never happy around these parts :slightly_smiling_face:

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
