### PR TITLE
RPM: Remove crio

### PR DESCRIPTION
**Pull request by lsm5**

### CODE REVIEW

**Comment by lsm5** [comment]
@saschagrunert @haircommander do we need the `Packaging for Fedora ...` cirrus jobs if we have packit?

**Comment by saschagrunert** [comment]
@lsm5 I don't think so.

**Review by mdbooth — COMMENTED** [review]
IIUC this meets the packaging requirements, namely not to touch `%{_libexecdir}/crio`, which is owned by crio. If the podman tests still pass, which from the discussion we seem confident they will, this looks good to me.

**Comment by lsm5** [comment]
> IIUC this meets the packaging requirements, namely not to touch `%{_libexecdir}/crio`, which is owned by crio. If the podman tests still pass, which from the discussion we seem confident they will, this looks good to me.

Could you please point to the exact `podman tests` in this repo? We can and probably should replace any Cirrus tests with TMT.

**Comment by lsm5** [comment]
PTAL.

**Comment by mdbooth** [comment]
> > IIUC this meets the packaging requirements, namely not to touch `%{_libexecdir}/crio`, which is owned by crio. If the podman tests still pass, which from the discussion we seem confident they will, this looks good to me.
> 
> Could you please point to the exact `podman tests` in this repo? We can and probably should replace any Cirrus tests with TMT.

Sorry, this was just my hand-wavy assumption that they must exist somewhere and will be executed here. I believe the primary concern about this change is that it could break podman (but we don't believe it will because podman is using a different conmon binary).

I did notice that there appear to be some podman tests in the Fedora repo here: https://src.fedoraproject.org/rpms/conmon/blob/rawhide/f/tests. I don't know what they do, though.

**Comment by lsm5** [comment]
> > > IIUC this meets the packaging requirements, namely not to touch `%{_libexecdir}/crio`, which is owned by crio. If the podman tests still pass, which from the discussion we seem confident they will, this looks good to me.
> > 
> > 
> > Could you please point to the exact `podman tests` in this repo? We can and probably should replace any Cirrus tests with TMT.
> 
> Sorry, this was just my hand-wavy assumption that they must exist somewhere and will be executed here. I believe the primary concern about this change is that it could break podman (but we don't believe it will because podman is using a different conmon binary).
> 
> I did notice that there appear to be some podman tests in the Fedora repo here: https://src.fedoraproject.org/rpms/conmon/blob/rawhide/f/tests. I don't know what they do, though.

Ack. I guess we can leave TMT enablement and cirrus removal for another PR. This PR should be good to go.

**Review by saschagrunert — APPROVED** [review]
@haircommander PTAL

**Comment by mdbooth** [comment]
Awesome, thanks! @lsm5 Any idea which version of Fedora this is likely to land in?

**Comment by lsm5** [comment]
> Awesome, thanks! @lsm5 Any idea which version of Fedora this is likely to land in?

@saschagrunert @haircommander is it worth cutting a new conmon for this? If not, I can add it manually.

**Comment by mdbooth** [comment]
> > Awesome, thanks! @lsm5 Any idea which version of Fedora this is likely to land in?
> 
> @saschagrunert @haircommander is it worth cutting a new conmon for this? If not, I can add it manually.

To reiterate my use case: I cannot switch to the k8s cri-o packages until I update my base OS (Fedora CoreOS) to a release including this change.

**Comment by lsm5** [comment]
> To reiterate my use case: I cannot switch to the k8s cri-o packages until I update my base OS (Fedora CoreOS) to a release including this change.

@mdbooth updates created https://bodhi.fedoraproject.org/updates/?search=conmon .

**Pull request merged**
